export const ADD_TICKET = "ADD_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const RANDOM_TICKET = "RANDOM_TICKET";
export const ADD_TICKET_FAIL = "ADD_TICKET_FAIL";
export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL";
